export default interface GameData {
  titleEn: string,
  titleJp: string,
  titleJpRomaji: string,
  genre: string,
  description: string,
  developer: string,
  publisher: string,
  gameplayStillUrl: string,
  gameplayGifUrl: string,
  boxArtUrl: string,
  releaseDate: string,
  sizeRomInMebibits: number,
  sizeSramInKibibits: number,
  isHiRom: boolean,
  isFastRom: boolean,
  specialChips: string[],
  funFacts: string[],
}